web:
  port: 2020

endpoints:
  - name: home.hoenle.xyz
    group: dns-01
    url: "192.168.178.5"
    interval: 1m
    dns:
      query-name: "home.hoenle.xyz"
      query-type: "A"
    conditions:
      - "[BODY] == 192.168.178.5"
      - "[DNS_RCODE] == NOERROR"
  
  - name: external
    group: dns-01
    url: "192.168.178.5"
    interval: 1m
    dns:
      query-name: "google.com"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"
  
  - name: home.hoenle.xyz
    group: dns-02
    url: "192.168.178.4"
    interval: 1m
    dns:
      query-name: "home.hoenle.xyz"
      query-type: "A"
    conditions:
      - "[BODY] == 192.168.178.5"
      - "[DNS_RCODE] == NOERROR"
  
  - name: external
    group: dns-02
    url: "192.168.178.4"
    interval: 1m
    dns:
      query-name: "google.com"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"

  - name: hoenle.xyz
    url: "https://hoenle.xyz"
    interval: 6h
    conditions:
      - "[DOMAIN_EXPIRATION] > 720h"
 
  - name: Blog
    group: web
    url: "https://hoenle.xyz"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 300"
      - "[CERTIFICATE_EXPIRATION] > 240h"
  
  - name: Homer
    group: selfhosted
    url: "https://home.hoenle.xyz"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 300"
      - "[CERTIFICATE_EXPIRATION] > 240h"
  
  - name: Paperless
    group: selfhosted
    url: "https://paperless.home.hoenle.xyz"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 300"
      - "[CERTIFICATE_EXPIRATION] > 240h"
  
  - name: Nextcloud
    group: selfhosted
    url: "https://cloud.home.hoenle.xyz"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 300"
      - "[CERTIFICATE_EXPIRATION] > 240h"
  
  - name: Tandoor recipes
    group: selfhosted
    url: "https://recipes.home.hoenle.xyz"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 300"
      - "[CERTIFICATE_EXPIRATION] > 240h"
  
  - name: Hedgedoc
    group: selfhosted
    url: "https://pad.home.hoenle.xyz"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 300"
      - "[CERTIFICATE_EXPIRATION] > 240h"

  - name: "Homepage SHW BK"
    group: bergkapelle
    url: "https://shw-bergkapelle.de"
    interval: 15m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 300"
      - "[CERTIFICATE_EXPIRATION] > 240h"

  - name: "Nextcloud SHW BK"
    group: bergkapelle
    url: "https://cloud.shw-bergkapelle.de"
    interval: 15m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 300"
      - "[CERTIFICATE_EXPIRATION] > 240h"
